// @vitest-environment jsdom
import { describe, it, expect, afterEach } from 'vitest';
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { ApprovalPanel } from './ApprovalPanel';
import type { ActiveSession } from '../../../lib/rbac/activeSessionStore';

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

let container: HTMLDivElement | null = null;
let root: Root | null = null;

afterEach(() => {
  act(() => {
    root?.unmount();
  });
  container?.remove();
  container = null;
  root = null;
});

function baseProps(activeSession: ActiveSession | null) {
  return {
    reportDate: '2026-09-18',
    snapshot: null,
    loading: false,
    message: null,
    canApprove: false,
    onGenerate: () => {},
    onApprove: () => {},
    onReject: () => {},
    canUnlockApproved: false,
    hqEditMessage: null,
    onOpenHqEdit: () => {},
    onCloseHqEdit: () => {},
    showSignatureWarning: false,
    activeSession,
  };
}

function mount(activeSession: ActiveSession | null) {
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  act(() => {
    root!.render(<ApprovalPanel {...baseProps(activeSession)} />);
  });
}

describe('ApprovalPanel — Generated By prefill', () => {
  it('prefills the Generated By input with the logged-in account display name before a snapshot exists', () => {
    mount({ userId: 'DEV-HQ-001', roleCode: 'SYSTEM_ADMIN', homeLocation: 'HQ' });
    const input = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    expect(input.value).toBe('Choi Hong-joon');
  });

  it('falls back to an empty string when there is no active session', () => {
    mount(null);
    const input = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    expect(input.value).toBe('');
  });

  it('remains freely editable after prefill', () => {
    mount({ userId: 'DEV-HQ-001', roleCode: 'SYSTEM_ADMIN', homeLocation: 'HQ' });
    const input = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    const nativeValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')!.set!;
    act(() => {
      nativeValueSetter.call(input, 'Manual Override');
      input.dispatchEvent(new Event('input', { bubbles: true }));
    });
    expect(input.value).toBe('Manual Override');
  });
});
