// @vitest-environment jsdom
import { describe, it, expect, afterEach } from 'vitest';
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { ApprovalPanel } from './ApprovalPanel';
import type { ActiveSession } from '../../../lib/rbac/activeSessionStore';

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

let container: HTMLDivElement | null = null;
let root: Root | null = null;

afterEach(() => {
  act(() => {
    root?.unmount();
  });
  container?.remove();
  container = null;
  root = null;
});

function baseProps(activeSession: ActiveSession | null) {
  return {
    reportDate: '2026-09-18',
    snapshot: null,
    loading: false,
    message: null,
    canApprove: false,
    onGenerate: () => {},
    onApprove: () => {},
    onReject: () => {},
    canUnlockApproved: false,
    hqEditMessage: null,
    onOpenHqEdit: () => {},
    onCloseHqEdit: () => {},
    showSignatureWarning: false,
    activeSession,
  };
}

function mount(activeSession: ActiveSession | null) {
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  act(() => {
    root!.render(<ApprovalPanel {...baseProps(activeSession)} />);
  });
}

const adminSession: ActiveSession = { employeeId: 'ADMIN-001', roleCode: 'ADMIN', homeLocation: 'HQ', permissions: {} };

describe('ApprovalPanel — Generated By prefill', () => {
  // Stage 3 (2026-09-19): USER_ACCOUNTS (the legacy PIN roster) is no longer
  // consulted — its userId keys aren't the same ID space as the Stage 1
  // employeeId ActiveSession now carries (see ApprovalPanel.tsx's
  // defaultGeneratedByName header comment). Prefill is inert until
  // personnel_master.full_name is exposed to the client; the field remains
  // freely editable either way.
  it('leaves the Generated By input blank even with an active session (no personnel_master name source yet)', () => {
    mount(adminSession);
    const input = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    expect(input.value).toBe('');
  });

  it('falls back to an empty string when there is no active session', () => {
    mount(null);
    const input = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    expect(input.value).toBe('');
  });

  it('remains freely editable', () => {
    mount(adminSession);
    const input = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    const nativeValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')!.set!;
    act(() => {
      nativeValueSetter.call(input, 'Manual Override');
      input.dispatchEvent(new Event('input', { bubbles: true }));
    });
    expect(input.value).toBe('Manual Override');
  });
});
