// src/cmms-daily-ops/components/report/ApprovalPanel.tsx
//
// PURPOSE
//   Phase 12 Pre-Flight III — DRAFT/SUBMITTED/APPROVED 상태 배지 + "Generate
//   Daily Report" 입력 + Site Manager 승인 버튼 + 승인 완료 락 배너.
//   useDailyReportApproval.ts가 넘겨주는 상태/액션만 렌더링하는 순수 UI 계층.

'use client';

import { useState } from 'react';
import { BEVEL_BUTTON, SUNKEN_INPUT, RAISED_PANEL } from '../../../components/cmms/scadaStyles';
import GuardrailBlockedBanner from '../../../components/shared/GuardrailBlockedBanner';
import type { DailyReportSnapshotSummary } from '../../hooks/useDailyReportApproval';

const STATUS_LABEL: Record<DailyReportSnapshotSummary['status'], string> = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED (서명 완료 · 승인 대기)',
  APPROVED: 'APPROVED (Site Manager 승인 완료)',
};

const STATUS_BADGE: Record<DailyReportSnapshotSummary['status'], string> = {
  DRAFT: 'bg-slate-200 text-slate-700',
  SUBMITTED: 'bg-amber-200 text-amber-900',
  APPROVED: 'bg-emerald-200 text-emerald-900',
};

export interface ApprovalPanelProps {
  reportDate: string;
  snapshot: DailyReportSnapshotSummary | null;
  loading: boolean;
  message: string | null;
  canApprove: boolean;
  onGenerate: (generatedBy: string) => void;
  onApprove: () => void;
  onReject: (reasonText: string) => void;
  canUnlockApproved: boolean;
  hqEditMessage: string | null;
  onOpenHqEdit: (reasonText: string) => void;
  onCloseHqEdit: (summaryText: string) => void;
  /** D-ADD-4 — true when lastRegeneratedAt is later than any signature's signed_at, regardless of status. */
  showSignatureWarning: boolean;
}

export function ApprovalPanel({
  reportDate,
  snapshot,
  loading,
  message,
  canApprove,
  onGenerate,
  onApprove,
  onReject,
  canUnlockApproved,
  hqEditMessage,
  onOpenHqEdit,
  onCloseHqEdit,
  showSignatureWarning,
}: ApprovalPanelProps) {
  const [generatedBy, setGeneratedBy] = useState('');
  const [rejectReason, setRejectReason] = useState('');
  const [hqUnlockReason, setHqUnlockReason] = useState('');
  const [hqCloseSummary, setHqCloseSummary] = useState('');

  return (
    <div className={`${RAISED_PANEL} p-3 space-y-2`}>
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="text-[11px] font-bold uppercase text-slate-700">Daily Report — {reportDate}</div>
        {snapshot && (
          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-none ${STATUS_BADGE[snapshot.status]}`}>
            {STATUS_LABEL[snapshot.status]}
          </span>
        )}
        {snapshot && showSignatureWarning && (
          <span className="text-[10px] font-bold px-2 py-0.5 rounded-none bg-red-200 text-red-900">
            재발행됨 — 서명 확인 필요
          </span>
        )}
      </div>

      {message && <GuardrailBlockedBanner message={message} variant={message.includes('완료') ? 'warning' : 'error'} />}

      {snapshot?.status === 'APPROVED' && !snapshot.hqEditUnlockActive && (
        <GuardrailBlockedBanner
          message={`${reportDate} 리포트는 Site Manager 승인으로 잠겼습니다 — 패트롤 데이터 수정 및 리포트 재생성이 모두 차단됩니다.`}
          variant="warning"
        />
      )}

      {snapshot?.status === 'APPROVED' && snapshot.hqEditUnlockActive && (
        <GuardrailBlockedBanner
          message={`${reportDate} 리포트는 현재 HQ 수정 중입니다 — 패트롤 데이터 수정 및 리포트 재생성이 임시로 허용됩니다.`}
          variant="warning"
        />
      )}

      {hqEditMessage && <GuardrailBlockedBanner message={hqEditMessage} variant={hqEditMessage.includes('완료') || hqEditMessage.includes('열렸습니다') ? 'warning' : 'error'} />}

      {!snapshot && (
        <div className="flex gap-2 items-center">
          <input
            value={generatedBy}
            onChange={(e) => setGeneratedBy(e.target.value)}
            placeholder="Generated By"
            className={SUNKEN_INPUT}
          />
          <button type="button" onClick={() => onGenerate(generatedBy)} className={BEVEL_BUTTON}>
            Generate Daily Report
          </button>
        </div>
      )}

      {snapshot && (
        <div className="text-[11px] font-mono text-slate-600">
          Generated by {snapshot.generatedBy} at {snapshot.generatedAt}
        </div>
      )}

      {snapshot?.status === 'SUBMITTED' && (
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={onApprove}
            disabled={!canApprove}
            className={`${BEVEL_BUTTON} ${!canApprove ? 'opacity-50 cursor-not-allowed' : ''}`}
            title={canApprove ? undefined : 'Site Manager / Acting Site Manager 권한이 필요합니다.'}
          >
            Approve (Site Manager)
          </button>
          <input
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
            placeholder="반려 사유"
            className={SUNKEN_INPUT}
          />
          <button
            type="button"
            onClick={() => onReject(rejectReason)}
            disabled={!canApprove}
            className={`${BEVEL_BUTTON} ${!canApprove ? 'opacity-50 cursor-not-allowed' : ''}`}
            title={canApprove ? undefined : 'Site Manager / Acting Site Manager 권한이 필요합니다.'}
          >
            반려 (Reject)
          </button>
        </div>
      )}

      {snapshot?.status === 'APPROVED' && canUnlockApproved && !snapshot.hqEditUnlockActive && (
        <div className="flex flex-wrap items-center gap-2">
          <input
            value={hqUnlockReason}
            onChange={(e) => setHqUnlockReason(e.target.value)}
            placeholder="HQ 수정 사유"
            className={SUNKEN_INPUT}
          />
          <button type="button" onClick={() => onOpenHqEdit(hqUnlockReason)} className={BEVEL_BUTTON}>
            HQ 수정 모드 열기
          </button>
        </div>
      )}

      {snapshot?.status === 'APPROVED' && canUnlockApproved && snapshot.hqEditUnlockActive && (
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] font-bold px-2 py-0.5 rounded-none bg-amber-200 text-amber-900">HQ 수정 중</span>
          <input
            value={hqCloseSummary}
            onChange={(e) => setHqCloseSummary(e.target.value)}
            placeholder="수정 완료 요약"
            className={SUNKEN_INPUT}
          />
          <button type="button" onClick={() => onCloseHqEdit(hqCloseSummary)} className={BEVEL_BUTTON}>
            수정 완료 &amp; 통보
          </button>
        </div>
      )}

      {loading && <div className="text-[10px] text-slate-400">Loading...</div>}
    </div>
  );
}
