// src/cmms-daily-ops/components/report/ApprovalPanel.tsx
//
// PURPOSE
//   Phase 12 Pre-Flight III — DRAFT/SUBMITTED/APPROVED 상태 배지 + "Generate
//   Daily Report" 입력 + Site Manager 승인 버튼 + 승인 완료 락 배너.
//   useDailyReportApproval.ts가 넘겨주는 상태/액션만 렌더링하는 순수 UI 계층.

'use client';

import { useState } from 'react';
import { BEVEL_BUTTON, SUNKEN_INPUT, RAISED_PANEL } from '../../../components/cmms/scadaStyles';
import GuardrailBlockedBanner from '../../../components/shared/GuardrailBlockedBanner';
import type { DailyReportSnapshotSummary } from '../../hooks/useDailyReportApproval';

const STATUS_LABEL: Record<DailyReportSnapshotSummary['status'], string> = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED (서명 완료 · 승인 대기)',
  APPROVED: 'APPROVED (Site Manager 승인 완료)',
};

const STATUS_BADGE: Record<DailyReportSnapshotSummary['status'], string> = {
  DRAFT: 'bg-slate-200 text-slate-700',
  SUBMITTED: 'bg-amber-200 text-amber-900',
  APPROVED: 'bg-emerald-200 text-emerald-900',
};

export interface ApprovalPanelProps {
  reportDate: string;
  snapshot: DailyReportSnapshotSummary | null;
  loading: boolean;
  message: string | null;
  canApprove: boolean;
  onGenerate: (generatedBy: string) => void;
  onApprove: () => void;
}

export function ApprovalPanel({ reportDate, snapshot, loading, message, canApprove, onGenerate, onApprove }: ApprovalPanelProps) {
  const [generatedBy, setGeneratedBy] = useState('');

  return (
    <div className={`${RAISED_PANEL} p-3 space-y-2`}>
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="text-[11px] font-bold uppercase text-slate-700">Daily Report — {reportDate}</div>
        {snapshot && (
          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-none ${STATUS_BADGE[snapshot.status]}`}>
            {STATUS_LABEL[snapshot.status]}
          </span>
        )}
      </div>

      {message && <GuardrailBlockedBanner message={message} variant={message.includes('완료') ? 'warning' : 'error'} />}

      {snapshot?.status === 'APPROVED' && (
        <GuardrailBlockedBanner
          message={`${reportDate} 리포트는 Site Manager 승인으로 잠겼습니다 — 패트롤 데이터 수정 및 리포트 재생성이 모두 차단됩니다.`}
          variant="warning"
        />
      )}

      {!snapshot && (
        <div className="flex gap-2 items-center">
          <input
            value={generatedBy}
            onChange={(e) => setGeneratedBy(e.target.value)}
            placeholder="Generated By"
            className={SUNKEN_INPUT}
          />
          <button type="button" onClick={() => onGenerate(generatedBy)} className={BEVEL_BUTTON}>
            Generate Daily Report
          </button>
        </div>
      )}

      {snapshot && (
        <div className="text-[11px] font-mono text-slate-600">
          Generated by {snapshot.generatedBy} at {snapshot.generatedAt}
        </div>
      )}

      {snapshot?.status === 'SUBMITTED' && (
        <button
          type="button"
          onClick={onApprove}
          disabled={!canApprove}
          className={`${BEVEL_BUTTON} ${!canApprove ? 'opacity-50 cursor-not-allowed' : ''}`}
          title={canApprove ? undefined : 'Site Manager / Acting Site Manager 권한이 필요합니다.'}
        >
          Approve (Site Manager)
        </button>
      )}

      {loading && <div className="text-[10px] text-slate-400">Loading...</div>}
    </div>
  );
}
