// src/cmms-daily-ops/views/LngEnergyOperationView.tsx
//
// PURPOSE
//   Stage C4 "LNG & NG Energy Operation" 탭 진입점 — Metering Train A/B
//   순찰 입력(Stage B1) + "Generate Daily Report" 액션(C1의 generateSnapshot
//   호출) + 생성 직후 인쇄 뷰(Stage C3) 표시.

'use client';

import { useState } from 'react';
import { BEVEL_BUTTON, SUNKEN_INPUT, RAISED_PANEL } from '../../components/cmms/scadaStyles';
import { MeteringPatrolForm } from '../components/patrol/MeteringPatrolForm';
import { NgBufferTankPatrolForm } from '../components/patrol/NgBufferTankPatrolForm';
import { usePatrolSaveHandler } from '../hooks/usePatrolSaveHandler';
import { DailyReportPrintView } from '../print/DailyReportPrintView';

const GENERATE_SNAPSHOT_API = '/api/v1/cmms/daily-report-snapshots';

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

export function LngEnergyOperationView() {
  const [reportDate] = useState(today);
  const [generatedBy, setGeneratedBy] = useState('');
  const [status, setStatus] = useState<string | null>(null);
  const [showReport, setShowReport] = useState(false);

  const onSaveTrainA = usePatrolSaveHandler('metering_train_a', reportDate, 'FIELD OP-1');
  const onSaveTrainB = usePatrolSaveHandler('metering_train_b', reportDate, 'FIELD OP-1');
  const onSaveNgBufferTank = usePatrolSaveHandler('ng_buffer_tank', reportDate, 'FIELD OP-1');

  async function handleGenerate() {
    if (!generatedBy.trim()) {
      setStatus('이름을 입력하세요.');
      return;
    }
    const res = await fetch(GENERATE_SNAPSHOT_API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ reportDate, generatedBy }),
    });
    const json = await res.json();
    if (!json.success) {
      setStatus(json.error ?? '리포트 생성 실패');
      return;
    }
    setStatus('리포트가 생성되었습니다.');
    setShowReport(true);
  }

  return (
    <div className="p-4 space-y-4">
      <h2 className="text-sm font-black uppercase text-slate-800">LNG &amp; NG Energy Operation</h2>
      <MeteringPatrolForm train="A" onSave={onSaveTrainA} />
      <MeteringPatrolForm train="B" onSave={onSaveTrainB} />
      <NgBufferTankPatrolForm onSave={onSaveNgBufferTank} />

      <div className={`${RAISED_PANEL} p-3 space-y-2`}>
        <div className="text-[11px] font-bold uppercase text-slate-700">Generate Daily Report — {reportDate}</div>
        <input
          value={generatedBy}
          onChange={(e) => setGeneratedBy(e.target.value)}
          placeholder="Generated By"
          className={SUNKEN_INPUT}
        />
        <button type="button" onClick={handleGenerate} className={BEVEL_BUTTON}>
          Generate Daily Report
        </button>
        {status && <div className="text-[11px] text-slate-600">{status}</div>}
      </div>

      {showReport && <DailyReportPrintView reportDate={reportDate} />}
    </div>
  );
}
