// @vitest-environment jsdom
import { describe, it, expect, afterEach, vi } from 'vitest';
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { LngEnergyOperationView } from './LngEnergyOperationView';
import { __resetDailyOpsPatrolStoreForTests } from '../state/useDailyOpsPatrolStore';

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

let container: HTMLDivElement | null = null;
let root: Root | null = null;

afterEach(() => {
  act(() => {
    root?.unmount();
  });
  container?.remove();
  container = null;
  root = null;
  __resetDailyOpsPatrolStoreForTests();
  vi.unstubAllGlobals();
});

const SAMPLE_PAYLOAD = {
  reportDate: '2026-09-14',
  generatedAt: '2026-09-14T00:00:00Z',
  generatedBy: 'HJ',
  domains: {},
  stationTotal: { volumeFlowrateMmscfd: 0, energyFlowrateMmbtud: 0, volumeTotalMmcf: 0, volumeTotalMscf: 0, energyTotalMmbtu: 0 },
};

function stubFetch(generateSuccess: boolean) {
  const postCalls: string[] = [];
  vi.stubGlobal(
    'fetch',
    vi.fn((url: string, init?: RequestInit) => {
      postCalls.push(url);
      if (url.includes('daily-report-snapshots') && init?.method === 'POST') {
        return Promise.resolve({
          ok: generateSuccess,
          json: async () =>
            generateSuccess
              ? { success: true, snapshot: { id: 1 }, payload: SAMPLE_PAYLOAD }
              : { success: false, error: 'already finalized' },
        } as Response);
      }
      if (url.includes('daily-report-snapshots')) {
        return Promise.resolve({
          ok: true,
          json: async () => ({ success: true, snapshot: { id: 1, payload: SAMPLE_PAYLOAD } }),
        } as Response);
      }
      return Promise.resolve({ ok: true, json: async () => ({ success: true, records: [] }) } as Response);
    })
  );
  return postCalls;
}

async function mountAndFlush() {
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  await act(async () => {
    root!.render(<LngEnergyOperationView />);
    await Promise.resolve();
  });
}

describe('LngEnergyOperationView', () => {
  it('renders both Metering Train A and B forms', async () => {
    stubFetch(true);
    await mountAndFlush();
    expect(container!.textContent).toContain('METERING-TRAIN-A');
    expect(container!.textContent).toContain('METERING-TRAIN-B');
  });

  it('requires a name before generating the report', async () => {
    stubFetch(true);
    await mountAndFlush();

    const generateButton = Array.from(container!.querySelectorAll('button')).find(
      (b) => b.textContent === 'Generate Daily Report'
    )!;
    act(() => {
      generateButton.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });

    expect(container!.textContent).toContain('이름을 입력하세요');
  });

  it('shows the print view after a successful generate', async () => {
    stubFetch(true);
    await mountAndFlush();

    const nameInput = container!.querySelector('input[placeholder="Generated By"]') as HTMLInputElement;
    const nativeSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')!.set!;
    act(() => {
      nativeSetter.call(nameInput, 'HJ');
      nameInput.dispatchEvent(new Event('input', { bubbles: true }));
    });

    const generateButton = Array.from(container!.querySelectorAll('button')).find(
      (b) => b.textContent === 'Generate Daily Report'
    )!;
    await act(async () => {
      generateButton.dispatchEvent(new MouseEvent('click', { bubbles: true }));
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(container!.textContent).toContain('리포트가 생성되었습니다');
  });
});
