// src/utils/excelExporter.ts

/**
 * Universal Excel & CSV Export Engine for Nias LNG Terminal Operational Data
 * Generates RFC-4180 compliant CSVs with UTF-8 BOM (\uFEFF) for immediate Excel compatibility
 * without character corruption or timezone drift.
 */

export interface ExportColumn<T> {
  header: string;
  accessor: keyof T | ((row: T) => string | number | boolean | null | undefined);
  unit?: string;
}

/**
 * Exports any dataset to a clean, Excel-formatted CSV with explicit column headers and units
 */
export function exportDatasetToCSV<T extends Record<string, unknown>>(
  filename: string,
  data: T[],
  columns?: ExportColumn<T>[],
  metadataHeader?: { title: string; generatedBy?: string; period?: string }
) {
  if (!data || data.length === 0) {
    alert('No data records available to export.');
    return;
  }

  const lines: string[] = [];

  // Optional Metadata Banner for Corporate Reporting
  if (metadataHeader) {
    lines.push(`"# NIAS LNG TERMINAL - OPERATIONAL REPORT: ${metadataHeader.title.replace(/"/g, '""')}"`);
    if (metadataHeader.period) {
      lines.push(`"# Reporting Period / Date: ${metadataHeader.period.replace(/"/g, '""')}"`);
    }
    const localTime = new Date().toLocaleString('en-GB', { timeZone: 'Asia/Jakarta' });
    lines.push(`"# Exported At: ${localTime} WIB (UTC+7)"`);
    if (metadataHeader.generatedBy) {
      lines.push(`"# Generated By: ${metadataHeader.generatedBy.replace(/"/g, '""')}"`);
    }
    lines.push('""'); // Empty line delimiter
  }

  // Header and Unit Rows
  if (columns && columns.length > 0) {
    const headers = columns.map((col) => `"${col.header.replace(/"/g, '""')}"`);
    lines.push(headers.join(','));

    // Check if any column specifies units
    const hasUnits = columns.some((col) => Boolean(col.unit));
    if (hasUnits) {
      const unitRow = columns.map((col) => `"[ ${col.unit || '-'} ]"`);
      lines.push(unitRow.join(','));
    }

    // Data Rows
    data.forEach((row) => {
      const rowValues = columns.map((col) => {
        let val: unknown;
        if (typeof col.accessor === 'function') {
          val = col.accessor(row);
        } else {
          val = row[col.accessor];
        }

        if (val === null || val === undefined) return '""';
        if (typeof val === 'number') return String(val);
        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
        const strVal = String(val).replace(/"/g, '""');
        return `"${strVal}"`;
      });
      lines.push(rowValues.join(','));
    });
  } else {
    // Fallback automatic key discovery
    const keys = Object.keys(data[0]);
    lines.push(keys.map((k) => `"${k}"`).join(','));
    data.forEach((row) => {
      const rowValues = keys.map((k) => {
        const val = row[k];
        if (val === null || val === undefined) return '""';
        if (typeof val === 'number') return String(val);
        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
        return `"${String(val).replace(/"/g, '""')}"`;
      });
      lines.push(rowValues.join(','));
    });
  }

  // Generate downloadable Blob with UTF-8 BOM (\uFEFF)
  const csvContent = '\uFEFF' + lines.join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.setAttribute('href', url);
  const finalFilename = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  link.setAttribute('download', finalFilename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Master Comprehensive Excel Export: Packs All Field Inspection, FloBoss, GC,
 * and Mass Balance records into a combined multi-section workbook format.
 */
export function exportAllTerminalLogsToExcel(payload: {
  inspectionLogs: Record<string, unknown>[];
  flobossLogs: Record<string, unknown>[];
  gcLogs: Record<string, unknown>[];
  settlementLogs: Record<string, unknown>[];
  operatorName?: string;
}) {
  const timestamp = new Date().toISOString().slice(0, 10);
  const localWibTime = new Date().toLocaleString('en-GB', { timeZone: 'Asia/Jakarta' });

  const lines: string[] = [];

  // 1. Workbook Title Banner
  lines.push(`"# =========================================================================="`);
  lines.push(`"# NIAS LNG TERMINAL - COMPREHENSIVE OPERATIONAL & CUSTODY TRANSFER DATASET"`);
  lines.push(`"# Export Date: ${timestamp} (${localWibTime} WIB / UTC+7)"`);
  lines.push(`"# Operator / Station: ${payload.operatorName || 'Nias Field Terminal Operations (STATION 01)'}"`);
  lines.push(`"# =========================================================================="`);
  lines.push('""');

  // Section A: FloBoss Gas Analysis & Custody Metering Logs
  lines.push(`"# SECTION 1: FLOBOSS S600+ CUSTODY TRANSFER & DAILY METERING LOGS"`);
  if (payload.flobossLogs.length > 0) {
    const fbKeys = Object.keys(payload.flobossLogs[0]);
    lines.push(fbKeys.map((k) => `"${k}"`).join(','));
    payload.flobossLogs.forEach((row) => {
      lines.push(
        fbKeys
          .map((k) => {
            const v = row[k];
            if (v === null || v === undefined) return '""';
            if (typeof v === 'number') return String(v);
            return `"${String(v).replace(/"/g, '""')}"`;
          })
          .join(',')
      );
    });
  } else {
    lines.push(`"No FloBoss records found."`);
  }
  lines.push('""');

  // Section B: Plant Gas Chromatograph Breakdown
  lines.push(`"# SECTION 2: PLANT GAS CHROMATOGRAPH (GC) MOLECULAR COMPOSITION ANALYSIS"`);
  if (payload.gcLogs.length > 0) {
    const gcKeys = Object.keys(payload.gcLogs[0]);
    lines.push(gcKeys.map((k) => `"${k}"`).join(','));
    payload.gcLogs.forEach((row) => {
      lines.push(
        gcKeys
          .map((k) => {
            const v = row[k];
            if (v === null || v === undefined) return '""';
            if (typeof v === 'number') return String(v);
            return `"${String(v).replace(/"/g, '""')}"`;
          })
          .join(',')
      );
    });
  } else {
    lines.push(`"No GC records found."`);
  }
  lines.push('""');

  // Section C: 4-Hour Field Inspection Logs
  lines.push(`"# SECTION 3: 4-HOUR PERIODIC FIELD INSPECTION & TANK TELEMETRY LOGS"`);
  if (payload.inspectionLogs.length > 0) {
    const inspKeys = Object.keys(payload.inspectionLogs[0]);
    lines.push(inspKeys.map((k) => `"${k}"`).join(','));
    payload.inspectionLogs.forEach((row) => {
      lines.push(
        inspKeys
          .map((k) => {
            const v = row[k];
            if (v === null || v === undefined) return '""';
            if (typeof v === 'number') return String(v);
            return `"${String(v).replace(/"/g, '""')}"`;
          })
          .join(',')
      );
    });
  } else {
    lines.push(`"No inspection records found."`);
  }
  lines.push('""');

  // Section D: ISO Tank Mass Balance & Settlement Ledger
  lines.push(`"# SECTION 4: ISO TANK MASS BALANCE & SETTLEMENT AUDIT LEDGER"`);
  if (payload.settlementLogs.length > 0) {
    const setKeys = Object.keys(payload.settlementLogs[0]);
    lines.push(setKeys.map((k) => `"${k}"`).join(','));
    payload.settlementLogs.forEach((row) => {
      lines.push(
        setKeys
          .map((k) => {
            const v = row[k];
            if (v === null || v === undefined) return '""';
            if (typeof v === 'number') return String(v);
            return `"${String(v).replace(/"/g, '""')}"`;
          })
          .join(',')
      );
    });
  } else {
    lines.push(`"No settlement records found."`);
  }

  // Create and trigger download
  const csvContent = '\uFEFF' + lines.join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `NIAS_LNG_Full_Operational_Logs_${timestamp}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
