-- Seed: role_permissions (7 roles x 11 modules = 77 rows)
-- NOTE: This is an interpretive mapping derived from module-group-level source
-- descriptions, not a verbatim extraction. Review before running on production.

-- SYSTEM_ADMIN: full access to all modules
INSERT INTO role_permissions (role_code, module_code, can_read, can_create, can_update, can_delete, can_approve, is_read_only_forced) VALUES
('SYSTEM_ADMIN', 'HQ_OVERVIEW', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'LNG_PROCESS_OVERVIEW', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'EQUIPMENT_ASSET_REGISTRY', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'WORK_ORDER_DIRECTORY', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'MAINTENANCE_MRO_HUB', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'MANPOWER_DAILY_SHIFT', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'MANPOWER_ROTATION_TRACKER', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'PTW_PERMITS', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'SAFETY_GAS_TESTING', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'SAFETY_ERT_READINESS', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
('SYSTEM_ADMIN', 'SAFETY_OVERVIEW', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),

-- SITE_MANAGER: read all, create/update PTW+WO(row-level), approve PTW/WO/Shift/CAR
('SITE_MANAGER', 'HQ_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'LNG_PROCESS_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'EQUIPMENT_ASSET_REGISTRY', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'WORK_ORDER_DIRECTORY', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE),
('SITE_MANAGER', 'MAINTENANCE_MRO_HUB', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'MANPOWER_DAILY_SHIFT', TRUE, FALSE, TRUE, FALSE, TRUE, FALSE),
('SITE_MANAGER', 'MANPOWER_ROTATION_TRACKER', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'PTW_PERMITS', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE),
('SITE_MANAGER', 'SAFETY_GAS_TESTING', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'SAFETY_ERT_READINESS', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('SITE_MANAGER', 'SAFETY_OVERVIEW', TRUE, FALSE, TRUE, FALSE, TRUE, FALSE),

-- ACTING_SITE_MANAGER: mirrors SITE_MANAGER but approve limited to PTW Stage 4 / SM-absence approval
('ACTING_SITE_MANAGER', 'HQ_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'LNG_PROCESS_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'EQUIPMENT_ASSET_REGISTRY', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'WORK_ORDER_DIRECTORY', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'MAINTENANCE_MRO_HUB', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'MANPOWER_DAILY_SHIFT', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'MANPOWER_ROTATION_TRACKER', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'PTW_PERMITS', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE),
('ACTING_SITE_MANAGER', 'SAFETY_GAS_TESTING', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'SAFETY_ERT_READINESS', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('ACTING_SITE_MANAGER', 'SAFETY_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- OPERATION_TEAM_LEADER: site/operational modules only
('OPERATION_TEAM_LEADER', 'HQ_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'LNG_PROCESS_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'EQUIPMENT_ASSET_REGISTRY', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'WORK_ORDER_DIRECTORY', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'MAINTENANCE_MRO_HUB', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'MANPOWER_DAILY_SHIFT', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE),
('OPERATION_TEAM_LEADER', 'MANPOWER_ROTATION_TRACKER', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'PTW_PERMITS', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE),
('OPERATION_TEAM_LEADER', 'SAFETY_GAS_TESTING', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'SAFETY_ERT_READINESS', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('OPERATION_TEAM_LEADER', 'SAFETY_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- HSSE_OFFICER: safety/PTW modules only
('HSSE_OFFICER', 'HQ_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'LNG_PROCESS_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'EQUIPMENT_ASSET_REGISTRY', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'WORK_ORDER_DIRECTORY', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'MAINTENANCE_MRO_HUB', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'MANPOWER_DAILY_SHIFT', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'MANPOWER_ROTATION_TRACKER', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'PTW_PERMITS', TRUE, FALSE, TRUE, FALSE, TRUE, FALSE),
('HSSE_OFFICER', 'SAFETY_GAS_TESTING', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE),
('HSSE_OFFICER', 'SAFETY_ERT_READINESS', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
('HSSE_OFFICER', 'SAFETY_OVERVIEW', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),

-- WORK_LEADER_TECH: assigned WO + TBM sign only (row-level filtering required at query level)
('WORK_LEADER_TECH', 'HQ_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'LNG_PROCESS_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'EQUIPMENT_ASSET_REGISTRY', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'WORK_ORDER_DIRECTORY', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'MAINTENANCE_MRO_HUB', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'MANPOWER_DAILY_SHIFT', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'MANPOWER_ROTATION_TRACKER', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'PTW_PERMITS', TRUE, FALSE, FALSE, FALSE, TRUE, FALSE),
('WORK_LEADER_TECH', 'SAFETY_GAS_TESTING', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'SAFETY_ERT_READINESS', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('WORK_LEADER_TECH', 'SAFETY_OVERVIEW', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- HQ_SUPERVISOR_AUDITOR: read-only everywhere except own HQ_OVERVIEW home module (forced read-only on all Site modules)
('HQ_SUPERVISOR_AUDITOR', 'HQ_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('HQ_SUPERVISOR_AUDITOR', 'LNG_PROCESS_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'EQUIPMENT_ASSET_REGISTRY', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'WORK_ORDER_DIRECTORY', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'MAINTENANCE_MRO_HUB', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'MANPOWER_DAILY_SHIFT', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'MANPOWER_ROTATION_TRACKER', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'PTW_PERMITS', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'SAFETY_GAS_TESTING', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'SAFETY_ERT_READINESS', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE),
('HQ_SUPERVISOR_AUDITOR', 'SAFETY_OVERVIEW', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE);
